-- src/lib/supabase/seed-data.sql
INSERT INTO restaurants (
    name,
    description,
    cuisine,
    location,
    address,
    rating,
    price_level,
    opening_time,
    closing_time,
    first_table_time,
    images,
    active,
    featured
) VALUES
(
    'The Urban Grill',
    'Contemporary American cuisine featuring prime steaks and fresh seafood in an elegant setting with city views.',
    ARRAY['American', 'Steakhouse'],
    'Downtown',
    '123 Main Street',
    4.7,
    3,
    '17:00',
    '23:00',
    '17:00',
    ARRAY['/restaurant-placeholder.jpg'],
    true,
    true
),
(
    'Sakura Japanese',
    'Authentic Japanese dining experience offering fresh sushi, sashimi, and traditional hot dishes.',
    ARRAY['Japanese', 'Sushi'],
    'Midtown',
    '456 Park Avenue',
    4.8,
    4,
    '17:30',
    '22:30',
    '17:30',
    ARRAY['/restaurant-placeholder.jpg'],
    true,
    false
),
(
    'La Piazza',
    'Family-owned Italian restaurant serving homemade pasta and wood-fired pizzas.',
    ARRAY['Italian', 'Pizza'],
    'Uptown',
    '789 Broadway',
    4.5,
    2,
    '16:00',
    '22:00',
    '16:00',
    ARRAY['/restaurant-placeholder.jpg'],
    true,
    true
),
(
    'Spice Route',
    'Modern Indian cuisine with a twist, featuring traditional flavors in contemporary presentations.',
    ARRAY['Indian', 'Contemporary'],
    'Downtown',
    '321 Oak Street',
    4.6,
    3,
    '17:00',
    '23:00',
    '17:00',
    ARRAY['/restaurant-placeholder.jpg'],
    true,
    false
),
(
    'Le Petit Bistro',
    'Charming French bistro offering classic dishes and an extensive wine list.',
    ARRAY['French', 'Wine Bar'],
    'Midtown',
    '567 Maple Avenue',
    4.4,
    3,
    '17:30',
    '23:30',
    '17:30',
    ARRAY['/restaurant-placeholder.jpg'],
    true,
    true
);